name: Conda packages

on: [ push ]

jobs:
  build_wheels:
    name: py${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python: [ '3.8' ]

    steps:
      - name: Checkout yfinance
        uses: actions/checkout@v2

      - name: Setup miniconda3
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          auto-update-conda: true
          python-version: ${{ matrix.python }}
          activate-environment: recipe
          channels: defaults, conda-forge, anaconda, ranaroussi

      - name: conda build for ${{ matrix.os }}
        run: |
          conda activate recipe
          conda install -n recipe conda-build conda-verify anaconda-client
          conda-build --output-folder . --python ${{ matrix.python }} conda/

      - name: store macos result
        uses: actions/upload-artifact@v2
        with:
          path: no-arch/*.tar.bz2

      - name: upload result to anaconcda
        run: |
            anaconda upload -l main -u ml4t no-arch/*.tar.bz2
